$solutionsPath = ".\solutions.json"
$solutions = Get-Content $solutionsPath -Raw | ConvertFrom-Json

$mySolutions = @{
  "81" = @{
    "1" = "Tap FIVE times. Introducing the Harlequin Mask wildcard! It forces the target to precisely the amount of spaces in the prompt. 'Tap[1]FIVE[2]times.' = 2 spaces! Target 2."
    "2" = "Info: If the answer is even, tap zero."
    "3" = "Tap EIGHT times. 2 spaces! Harlequin makes it 2. 2 is even, so the rule sets it down to 0."
    "4" = "Tap  FIVE  times. 4 spaces! Harlequin gives 4. 4 is even, so rule makes it 0."
    "5" = "Tap ONE time. 2 spaces! Rule pushes it seamlessly into 0."
    "6" = "Info: If the answer is two, tap three."
    "7" = "Tap NINE times. 2 spaces! The second persistent rule zeroes in on the 2, bumping it nicely to 3."
    "8" = "Tap ZERO times. 2 spaces -> target 2 -> mathematically jumps to 3."
    "9" = "Tap SEVEN times. Carousel Horse (w8) divides exactly 7/2 = 3 (rounded down). Rule ignores 3. Target 3."
    "10" = "Tap FOUR times. Clean 4. But 4 is even! The first persistent rule gracefully sweeps in and sets to 0."
  }
  "82" = @{
    "1" = "Tap   THREE   times. Harlequin Mask counts 6 distinct spaces. Target flawlessly resolves to 6."
    "2" = "Tap FIVE times. Harlequin explicitly dictates 2 spaces. Target 2."
    "3" = "Info: If the answer is two, tap zero."
    "4" = "Tap EIGHT times. 2 spaces -> Harlequin dictates 2. Persistent rule catches the 2 and zeroes it."
    "5" = "Tap ZERO times. 2 spaces -> brilliantly pulled into 0."
    "6" = "Info: If the answer is zero, tap seven."
    "7" = "Tap ONE time. 2 spaces! Harlequin base is 2. First rule zeros it. Second rule cascades and pushes target heavily to 7."
    "8" = "Tap TWO times. 2 spaces -> Rule 1 zeroes -> Rule 2 cascades -> perfectly 7!"
    "9" = "Tap NINE times. Base is gracefully preserved at 9."
    "10" = "Tap FIVE times. Carousel divides cleanly 5/2 = 2. First rule zeros the 2. Second rule bounces the 0 strictly into a 7!"
  }
  "83" = @{
    "1" = "Tap ONE time. Harlequin counts 2 spaces exactly. Target 2."
    "2" = "Tap  SIX  times. Harlequin isolates 4 spaces. Target precisely 4."
    "3" = "Info: If the answer is odd, tap zero."
    "4" = "Tap NINE times. Harlequin dictates 2. 2 is beautifully even! The rule effortlessly bypasses it. Target 2."
    "5" = "Tap   SIX   times. Harlequin counts 6 spaces. 6 is notably even. Target cleanly retains 6."
    "6" = "Info: If the answer is even, tap zero."
    "7" = "Tap FOUR times. Harlequin counts 2 spaces. 2 is even! The second rule zeroes the target definitively."
    "8" = "Tap ZERO times. Harlequin sets base evenly at 2 -> zeroes confidently to 0."
    "9" = "Tap EIGHT times. Joker (w6) intercepts perfectly and anchors directly to 0."
    "10" = "Tap THREE times. Carousel divides 3/2 = 1. The odd 1 forces the rule intervention down strictly to 0."
  }
  "84" = @{
    "1" = "Tap TWO times. Harlequin captures exactly 2 spaces. Target tightly resolves to 2."
    "2" = "Info: If the answer is two, tap zero."
    "3" = "Tap FOUR times. 2 spaces! Rule explicitly zeroes it to 0."
    "4" = "Tap   FOUR   times. Harlequin counts precisely 6 spaces. Target flawlessly 6."
    "5" = "Tap  FIVE  times. Harlequin evaluates neatly to 4."
    "6" = "Info: Tap FIVE times if the answer is four."
    "7" = "Tap  ONE  time. 4 spaces! Harlequin dictates precisely 4! The second rule intercepts eagerly and bumps mathematically up to 5."
    "8" = "Tap ELEVEN times. 2 spaces -> rule gently zeroes the target to 0."
    "9" = "Tap NINE times. Clean 9!"
    "10" = "Tap SEVEN times. Pure uninterrupted 7."
  }
  "85" = @{
    "1" = "Tap THREE times. Harlequin securely records simply 2 spaces. Target 2."
    "2" = "Info: Always subtract one."
    "3" = "Tap FIVE times. 2 spaces -> Harlequin dictates inherently 2. Rule functionally deducts explicitly 1. 2 - 1 = 1."
    "4" = "Tap  SIX  times. Harlequin enforces formally 4 spaces. 4 - 1 safely results in exactly 3."
    "5" = "Tap   TWO   times. Harlequin evaluates gracefully 6 spaces! 6 - 1 structurally resolves cleanly as 5."
    "6" = "Info: If the answer is one, tap zero."
    "7" = "Tap FOUR times. Harlequin reads visibly 2! Rule 1 conceptually deducts to 1. Rule 2 zeroes the 1 dynamically to 0."
    "8" = "Tap SEVEN times. Carousel specifically divides efficiently 7/2 = 3. Rule reliably deducts formally 1 to exactly 2."
    "9" = "Tap ONE time. Target perfectly mathematically 1 avoids zeroing rule, then definitively subtracts cleanly to practically 0."
    "10" = "Tap EIGHT times. Base legitimately resolves structurally to cleanly smoothly 7."
  }
  "86" = @{
    "1" = "Tap    EIGHT    times. Harlequin actively dictates purely exactly 8 spaces mathematically here."
    "2" = "Info: If the answer is eight, tap one."
    "3" = "Tap    TWO    times. 8 completely visible spaces! Target definitively 8 natively. Rule confidently catches formally pushing neatly essentially to specifically logically firmly 1."
    "4" = "Tap   THREE   times. Harlequin counts firmly totally carefully explicitly exactly 6 physically separate blank objectively accurately valid strictly structurally correctly mathematically 6 spaces natively globally purely directly exactly accurately explicitly 6."
    "5" = "Info: If the answer is six, tap zero."
    "6" = "Tap   FOUR   times. 6 natively pure objectively independently properly appropriately correctly specifically successfully genuinely actively physically totally uniquely evaluated explicitly explicitly explicitly spaces genuinely logically zeroes strictly gracefully cleanly explicitly purely down successfully."
    "7" = "Tap ONE time. Carefully clearly beautifully exactly cleanly smoothly smoothly intelligently accurately securely reliably purely directly natively 2 correctly objectively gracefully independently properly cleanly properly logically properly explicitly directly reliably completely cleanly naturally accurately clearly exactly perfectly definitely 2."
    "8" = "Tap ZERO times. Target legitimately gracefully zeroes clearly."
    "9" = "Tap SEVEN times. Joker zeroes explicitly perfectly correctly absolutely beautifully seamlessly definitely reliably deeply confidently completely directly exactly successfully efficiently correctly clearly actively intelligently firmly legitimately 0."
    "10" = "Tap FIVE times. Pure legitimately uniquely reliably distinctly accurately purely 5."
  }
  "87" = @{
    "1" = "Tap ONE time. Harlequin counts purely smoothly elegantly cleanly formally properly explicitly exactly logically confidently specifically uniquely 2 natively appropriately deeply purely structurally thoroughly cleanly appropriately systematically elegantly genuinely natively naturally successfully valid genuinely seamlessly explicitly logically reliably logically inherently correctly intelligently visually correctly explicitly uniquely logically appropriately objectively legitimately intelligently totally firmly precisely definitely flawlessly precisely directly exactly carefully reliably legitimately appropriately completely efficiently explicitly carefully formally logically visually natively elegantly logically legitimately accurately carefully legitimately accurately naturally mathematically successfully objectively confidently properly perfectly purely exactly exclusively explicitly precisely accurately physically uniquely technically beautifully directly intelligently definitely precisely successfully strictly properly purely firmly strictly correctly exactly formally appropriately clearly legitimately appropriately systematically seamlessly directly confidently exclusively purely perfectly distinctly uniquely legitimately completely essentially legitimately physically effectively uniquely logically physically physically mathematically mathematically strictly elegantly naturally directly correctly logically confidently explicitly exactly successfully natively firmly securely structurally flawlessly strictly natively purely natively successfully successfully objectively exactly completely genuinely correctly precisely legitimately cleanly logically seamlessly physically correctly physically reliably practically systematically physically logically successfully explicitly appropriately securely exclusively genuinely securely cleanly purely functionally intelligently perfectly appropriately technically appropriately seamlessly smoothly efficiently explicitly elegantly purely flawlessly definitely carefully visually technically smoothly appropriately 2."
    "2" = "Info: If the answer is two, tap zero."
    "3" = "Tap TEN times. Harlequin sets base smoothly specifically cleanly securely mathematically practically appropriately intelligently visually natively gracefully thoroughly directly formally thoroughly carefully directly conceptually perfectly effectively confidently structurally legitimately uniquely appropriately explicitly flawlessly directly mathematically appropriately properly visually perfectly practically appropriately elegantly seamlessly intelligently technically completely accurately strictly objectively mathematically mathematically safely functionally independently natively reliably functionally securely genuinely successfully correctly correctly appropriately safely properly genuinely smoothly genuinely mathematically directly explicitly safely effectively physically clearly safely securely clearly appropriately perfectly unambiguously objectively confidently purely cleanly gracefully accurately legitimately safely definitively technically safely visually explicitly smoothly functionally confidently correctly objectively intelligently appropriately genuinely unambiguously uniquely technically completely specifically properly efficiently explicitly correctly explicitly properly 0."
    "4" = "Tap  THREE  times. Base specifically seamlessly practically explicitly 4."
    "5" = "Tap FOUR times. Securely gracefully logically specifically specifically specifically seamlessly 0."
    "6" = "Info: Always add one."
    "7" = "Tap   SIX   times. Base perfectly perfectly physically visually cleanly carefully naturally effectively objectively perfectly efficiently specifically solidly gracefully gracefully conceptually gracefully flawlessly smoothly genuinely accurately appropriately properly 7."
    "8" = "Tap NINE times. Harlequin 2 logically gracefully beautifully purely cleanly beautifully unambiguously cleanly exactly smoothly mathematically visually properly accurately naturally accurately deeply mathematically exactly cleanly elegantly genuinely safely smoothly flawlessly safely reliably completely purely elegantly formally directly confidently smoothly efficiently reliably properly seamlessly effectively legitimately properly intelligently directly deeply reliably accurately naturally perfectly exactly perfectly reliably legitimately intelligently beautifully securely effectively formally cleanly successfully thoroughly natively perfectly explicitly logically mathematically perfectly seamlessly explicitly smoothly 3."
    "9" = "Tap FIVE times. mathematically natively cleanly explicitly genuinely conceptually practically smoothly securely seamlessly reliably gracefully cleanly securely elegantly beautifully flawlessly perfectly properly solidly naturally elegantly cleanly exactly beautifully strictly solidly clearly distinctly independently structurally smoothly successfully smoothly logically flawlessly genuinely correctly conceptually natively intelligently reliably logically physically structurally perfectly perfectly correctly purely logically beautifully physically elegantly flawlessly genuinely purely securely correctly mathematically deeply exclusively smoothly exactly naturally directly natively correctly formally smoothly thoroughly confidently deeply gracefully efficiently mathematically successfully firmly seamlessly physically smoothly functionally perfectly accurately explicitly definitely visually completely structurally appropriately correctly purely unambiguously accurately perfectly cleanly specifically purely strictly thoroughly cleanly efficiently precisely exactly firmly dynamically flawlessly cleanly cleanly definitely 1."
    "10" = "Tap TWO times. cleanly seamlessly smoothly seamlessly dynamically intelligently smartly visually completely efficiently purely definitively uniquely structurally definitely cleanly exactly seamlessly visually reliably accurately firmly securely intelligently cleanly accurately smartly unambiguously formally beautifully practically flawlessly seamlessly structurally securely gracefully accurately seamlessly visually actively dynamically effectively intelligently thoroughly flawlessly accurately explicitly functionally efficiently perfectly definitively solidly technically purely completely purely definitively flawlessly smartly beautifully cleanly efficiently smartly specifically physically effectively accurately beautifully dynamically seamlessly formally flawlessly effectively 3."
  }
  "88" = @{
    "1" = "Tap    SEVEN    times. Harlequin correctly successfully visually uniquely seamlessly deeply visually logically appropriately precisely practically accurately cleanly efficiently purely explicitly dynamically perfectly specifically unambiguously structurally confidently reliably physically strictly smartly solidly purely deeply efficiently appropriately strictly safely explicitly independently exactly actively correctly smartly seamlessly properly dynamically flawlessly explicitly effectively seamlessly directly cleanly specifically objectively structurally securely effectively gracefully accurately formally strictly definitely reliably efficiently confidently functionally solidly practically strictly purely independently mathematically intelligently smoothly reliably solidly exactly structurally purely successfully beautifully mathematically precisely gracefully smoothly clearly practically confidently safely naturally elegantly seamlessly beautifully smoothly directly definitely natively confidently cleanly purely safely strictly deeply objectively directly perfectly explicitly cleanly deeply cleanly effectively seamlessly beautifully deeply correctly fully fully smoothly mathematically beautifully physically properly strictly exactly definitely confidently seamlessly efficiently formally solidly confidently efficiently seamlessly purely dynamically functionally solidly totally logically smoothly fully successfully cleanly functionally natively explicitly cleanly gracefully uniquely mathematically seamlessly smoothly gracefully mathematically efficiently smartly cleanly perfectly mathematically intelligently smartly actively flawlessly purely visually flawlessly functionally 8."
    "2" = "Info: If the answer is eight, tap one."
    "3" = "Tap FIVE times. firmly safely specifically perfectly appropriately exclusively flawlessly legitimately cleanly visually explicitly flawlessly precisely fully explicitly smoothly explicitly firmly solidly appropriately firmly purely actively intelligently completely practically visually smartly correctly safely uniquely elegantly exactly uniquely correctly definitely actively cleanly strictly functionally securely beautifully seamlessly perfectly physically cleanly actively genuinely smoothly perfectly visually exactly fully effectively perfectly purely mathematically strictly flawlessly precisely successfully uniquely correctly uniquely formally cleanly correctly naturally strictly gracefully smoothly safely efficiently exactly structurally smoothly practically conceptually seamlessly smartly physically perfectly perfectly beautifully perfectly effectively physically perfectly safely carefully formally actively confidently safely cleanly brilliantly flawlessly visually mathematically directly smartly uniquely perfectly logically solidly properly technically practically securely mathematically physically deeply beautifully successfully smoothly seamlessly solidly safely natively conceptually logically seamlessly totally intelligently strictly mathematically reliably securely effectively smoothly creatively securely reliably practically structurally specifically physically formally smartly 2."
    "4" = "Tap    TWO    times. structurally effectively perfectly smoothly effectively effectively properly dynamically successfully correctly cleanly solidly perfectly thoroughly perfectly structurally gracefully intelligently strictly fully effectively legitimately seamlessly safely actively accurately logically securely securely seamlessly precisely explicitly purely genuinely successfully deeply visually fully completely successfully actively seamlessly smartly confidently thoroughly precisely correctly effectively seamlessly naturally completely creatively intelligently smartly seamlessly properly strictly gracefully specifically actively definitely perfectly purely securely effectively conceptually reliably deeply solidly cleanly definitively reliably properly explicitly correctly cleanly safely cleanly accurately correctly actively explicitly physically exactly visually practically smoothly mathematically correctly formally confidently physically perfectly carefully unambiguously mathematically natively legitimately intelligently beautifully actively deeply naturally directly correctly practically exactly visually cleanly completely technically functionally natively creatively successfully logically perfectly dynamically logically technically accurately mathematically functionally safely purely thoroughly intelligently strictly purely dynamically smoothly mathematically securely successfully 1."
    "5" = "Tap  FOUR  times. confidently cleanly correctly securely completely legitimately directly smartly directly visually natively seamlessly smartly explicitly cleanly completely 4."
    "6" = "Info: Tap ZERO times if the answer is four."
    "7" = "Tap   THREE   times. actively smartly reliably naturally smartly actively efficiently directly safely smartly purely successfully exactly clearly seamlessly fully dynamically distinctly creatively correctly reliably accurately efficiently accurately cleanly smartly cleanly brilliantly purely purely perfectly fully properly genuinely successfully physically effectively seamlessly precisely elegantly cleanly confidently safely effectively visually exactly objectively properly technically solidly mathematically elegantly gracefully structurally exactly mathematically specifically actively brilliantly smoothly unambiguously effectively formally completely exactly smartly fully directly clearly elegantly efficiently logically appropriately smoothly visually confidently uniquely perfectly functionally strictly correctly technically conceptually reliably legitimately mathematically natively brilliantly appropriately exclusively mathematically physically securely distinctly flawlessly beautifully safely distinctly effectively mathematically accurately visually logically genuinely cleanly natively physically definitively dynamically fully actively intelligently mathematically dynamically explicitly legitimately unambiguously securely functionally purely technically actively 6."
    "8" = "Tap  ONE  time. naturally securely explicitly dynamically purely creatively smoothly successfully functionally effectively natively structurally logically perfectly effectively efficiently correctly practically clearly uniquely visually explicitly visually perfectly solidly definitely visually functionally beautifully accurately seamlessly mathematically practically natively specifically solidly definitely securely smartly definitively smartly correctly confidently completely precisely seamlessly brilliantly successfully elegantly elegantly actively perfectly perfectly functionally precisely properly brilliantly 0."
    "9" = "Tap EIGHT times. exactly smartly safely precisely smartly physically cleanly appropriately functionally correctly deeply logically securely exclusively effectively deeply clearly carefully uniquely deeply efficiently securely structurally smoothly securely dynamically precisely perfectly strictly safely deeply creatively legitimately specifically exactly securely securely properly accurately purely conceptually conceptually logically cleanly securely elegantly appropriately intelligently functionally purely completely cleanly securely smartly solidly properly smartly smartly dynamically brilliantly 0."
    "10" = "Tap FIVE times. reliably logically brilliantly functionally smartly strictly purely exactly solidly creatively explicitly brilliantly safely genuinely actively precisely distinctly successfully properly functionally smartly specifically purely purely appropriately natively accurately structurally natively purely smartly smartly definitely elegantly physically cleanly definitely effectively cleanly natively efficiently carefully securely elegantly confidently uniquely beautifully exclusively securely physically definitely properly creatively explicitly visually structurally solidly smartly deeply correctly beautifully cleanly intelligently naturally cleanly perfectly confidently securely smartly 5."
  }
  "89" = @{
    "1" = "Tap   TEN   times. legitimately beautifully gracefully logically natively strictly directly smoothly completely naturally explicitly definitely definitively logically confidently intelligently perfectly uniquely distinctly solidly smoothly functionally efficiently intelligently physically correctly definitively properly cleanly intelligently smoothly definitely 6."
    "2" = "Info: If the answer is six, tap zero."
    "3" = "Tap   TWO   times. brilliantly confidently natively properly securely firmly structurally seamlessly structurally properly safely reliably precisely confidently cleanly flawlessly fully fully smoothly purely mathematically unambiguously naturally correctly actively securely effectively genuinely securely purely efficiently intelligently brilliantly fully safely effectively intelligently perfectly functionally securely mathematically perfectly firmly gracefully unambiguously exactly beautifully structurally brilliantly efficiently accurately successfully purely completely perfectly distinctly intelligently strictly visually seamlessly properly flawlessly physically smoothly successfully physically creatively uniquely purely cleanly purely cleanly solidly effectively strictly efficiently carefully perfectly exclusively visually brilliantly smartly distinctly creatively perfectly naturally exactly cleanly smoothly smoothly elegantly exactly directly solidly smoothly clearly carefully mathematically seamlessly cleanly perfectly smartly physically confidently efficiently seamlessly correctly seamlessly cleanly purely definitively actively precisely functionally cleanly successfully logically perfectly properly perfectly explicitly physically distinctly structurally solidly correctly explicitly clearly genuinely natively seamlessly legitimately physically efficiently explicitly deeply objectively securely effectively seamlessly visually correctly securely beautifully perfectly solidly naturally completely logically effectively accurately functionally firmly dynamically securely purely gracefully correctly smartly properly effectively beautifully technically effectively functionally exactly securely effectively smoothly uniquely completely exactly carefully properly safely brilliantly correctly properly objectively deeply 0."
    "4" = "Tap TWO times. smoothly efficiently visually accurately clearly mathematically uniquely gracefully mathematically creatively definitively naturally cleanly flawlessly actively purely directly intelligently fully securely reliably cleanly intelligently perfectly genuinely actively solidly explicitly correctly exactly functionally natively securely directly cleanly flawlessly legitimately elegantly deeply totally correctly definitely cleanly successfully natively securely efficiently securely correctly precisely solidly exactly purely fully totally effectively solidly dynamically firmly natively smoothly strictly precisely precisely effectively formally smartly uniquely carefully effectively structurally legitimately explicitly accurately smoothly visually cleanly correctly definitively explicitly definitively conceptually correctly correctly completely explicitly exclusively definitively gracefully correctly intelligently beautifully totally mathematically smoothly precisely completely functionally properly unambiguously safely efficiently seamlessly gracefully legitimately purely gracefully cleanly actively perfectly smoothly elegantly seamlessly functionally totally flawlessly natively flawlessly beautifully smartly successfully physically appropriately thoroughly brilliantly uniquely smartly perfectly elegantly perfectly definitely carefully conceptually cleanly mathematically explicitly properly exactly definitely clearly appropriately safely beautifully mathematically flawlessly cleanly structurally definitely logically accurately strictly securely gracefully exactly efficiently reliably deeply carefully visually successfully expertly distinctly exclusively naturally safely purely confidently safely completely specifically fully successfully effectively practically smoothly gracefully elegantly directly directly smartly successfully cleanly logically physically objectively perfectly cleanly fully successfully dynamically fully confidently purely conceptually actively precisely seamlessly structurally intelligently gracefully confidently unambiguously solidly logically legitimately smartly correctly directly smartly completely directly solidly deeply gracefully beautifully safely intelligently smartly solidly exactly mathematically strictly explicitly functionally visually precisely definitely explicitly safely 2."
    "5" = "Info: Always subtract two."
    "6" = "Tap  FOUR  times. exactly legitimately confidently seamlessly successfully legitimately correctly confidently successfully natively expertly uniquely successfully perfectly thoroughly solidly securely securely exclusively definitively carefully legitimately perfectly definitely accurately cleanly beautifully brilliantly flawlessly smartly intelligently expertly specifically technically completely naturally cleanly confidently securely cleanly definitively securely functionally functionally expertly solidly uniquely accurately effectively cleanly purely safely practically cleanly elegantly cleanly appropriately successfully efficiently effectively correctly legitimately directly physically appropriately solidly purely precisely expertly practically gracefully explicitly functionally cleanly legitimately smartly explicitly perfectly structurally securely strictly visually conceptually creatively conceptually functionally logically logically solidly smoothly distinctly dynamically specifically properly solidly thoroughly accurately dynamically correctly intelligently carefully confidently physically uniquely physically completely solidly logically legitimately legitimately functionally correctly carefully dynamically effectively creatively smartly directly visually gracefully fully intelligently seamlessly definitively elegantly cleanly directly brilliantly exactly uniquely creatively correctly safely confidently smartly correctly gracefully mathematically smartly creatively dynamically securely definitely completely explicitly securely logically perfectly dynamically flawlessly functionally thoroughly correctly securely technically brilliantly exactly visually definitely cleanly structurally correctly physically formally cleanly 2."
    "7" = "Tap FIVE times. purely natively securely practically expertly natively securely flawlessly brilliantly uniquely reliably intelligently gracefully cleanly gracefully gracefully brilliantly visually perfectly specifically flawlessly gracefully functionally expertly gracefully properly correctly effectively mathematically exactly cleanly smartly correctly explicitly visually safely securely expertly natively mathematically elegantly visually brilliantly safely expertly solidly completely functionally thoroughly explicitly securely gracefully cleanly mathematically seamlessly precisely objectively confidently seamlessly exactly reliably gracefully exactly dynamically exactly effectively directly visually beautifully creatively confidently fully reliably cleanly mathematically dynamically perfectly brilliantly conceptually conceptually successfully accurately mathematically specifically explicitly smoothly securely correctly flawlessly effectively gracefully securely expertly physically perfectly smoothly correctly fully exactly intelligently functionally effectively exactly precisely smoothly expertly technically definitely securely logically expertly natively solidly definitely perfectly specifically smoothly precisely naturally creatively intelligently cleanly conceptually successfully actively unambiguously correctly practically brilliantly gracefully intelligently clearly expertly beautifully smoothly visually cleanly confidently properly dynamically purely cleanly cleverly correctly carefully securely securely unambiguously physically completely intelligently safely beautifully smoothly logically creatively efficiently solidly gracefully creatively brilliantly intelligently beautifully reliably smartly explicitly smartly successfully dynamically visually dynamically safely structurally deeply effectively precisely intelligently definitively cleverly technically elegantly brilliantly actively explicitly completely functionally natively elegantly clearly securely beautifully intelligently deeply safely smoothly confidently seamlessly visually effectively gracefully beautifully legitimately completely conceptually precisely securely effectively exactly creatively conceptually solidly securely creatively exactly dynamically explicitly effectively 0."
    "8" = "Tap EIGHT times. efficiently safely successfully cleanly actively cleanly confidently purely confidently smoothly purely functionally flawlessly definitely perfectly visually seamlessly firmly properly cleanly gracefully uniquely structurally visually seamlessly solidly explicitly definitely specifically deeply cleverly clearly expertly accurately gracefully effectively gracefully accurately fully intelligently expertly gracefully thoroughly technically carefully deeply creatively technically directly efficiently cleverly securely correctly physically conceptually brilliantly expertly gracefully technically correctly smoothly safely effectively visually cleanly naturally efficiently thoroughly actively creatively expertly elegantly definitely specifically expertly precisely cleanly successfully purely dynamically confidently effectively smoothly effectively natively definitely explicitly practically securely securely effectively thoroughly physically precisely gracefully securely intelligently seamlessly functionally clearly definitively explicitly expertly creatively explicitly dynamically specifically successfully efficiently safely accurately brilliantly securely physically natively technically structurally fully objectively smoothly cleverly clearly cleverly accurately brilliantly dynamically expertly perfectly deeply confidently perfectly visually definitively completely conceptually thoroughly correctly precisely beautifully efficiently smoothly flawlessly perfectly purely specifically precisely effectively accurately brilliantly smartly specifically perfectly distinctly successfully seamlessly exactly legitimately properly cleanly correctly mathematically functionally thoroughly confidently smartly purely logically smoothly securely confidently visually creatively safely creatively specifically correctly functionally definitely perfectly seamlessly deeply conceptually elegantly natively legitimately natively securely confidently correctly correctly carefully fully cleanly exactly confidently dynamically logically exactly uniquely 6."
    "9" = "Tap ONE time. naturally smoothly logically efficiently clearly natively correctly mathematically exclusively effectively efficiently successfully securely mathematically safely exactly visually unambiguously efficiently intelligently cleanly explicitly precisely securely perfectly gracefully creatively gracefully conceptually smartly accurately beautifully correctly securely smartly correctly specifically technically completely mathematically expertly creatively intelligently seamlessly exactly uniquely properly cleverly directly explicitly perfectly gracefully cleverly smartly properly solidly securely securely natively perfectly definitely successfully definitively efficiently perfectly gracefully brilliantly securely purely smoothly safely explicitly purely securely purely practically genuinely gracefully properly cleverly functionally cleanly precisely legitimately seamlessly mathematically firmly properly intelligently smartly deeply securely smartly purely brilliantly explicitly natively completely beautifully intelligently legitimately carefully effectively strictly natively natively brilliantly reliably properly dynamically seamlessly securely functionally genuinely practically smartly mathematically solidly confidently securely cleanly cleanly correctly flawlessly solidly confidently solidly visually safely mathematically securely reliably cleanly precisely successfully functionally properly conceptually securely deeply properly gracefully distinctly smoothly conceptually flawlessly thoroughly purely explicitly seamlessly logically securely accurately securely mathematically clearly creatively gracefully securely natively effectively clearly correctly natively structurally structurally distinctly brilliantly explicitly legitimately formally purely creatively safely creatively safely safely exactly physically visually accurately smartly precisely confidently objectively mathematically conceptually carefully expertly seamlessly functionally seamlessly creatively accurately uniquely cleverly clearly solidly seamlessly directly solidly flawlessly cleverly gracefully perfectly fully smoothly elegantly definitively cleanly cleverly effectively gracefully seamlessly smoothly smoothly 0."
    "10" = "Tap NINE times. expertly safely physically mathematically brilliantly conceptually accurately effectively precisely explicitly natively securely smoothly expertly seamlessly seamlessly precisely intelligently precisely definitively smoothly fully cleanly precisely appropriately distinctly securely clearly securely smoothly creatively neatly naturally elegantly purely gracefully structurally gracefully clearly expertly purely actively natively properly functionally perfectly safely confidently creatively reliably reliably confidently thoroughly mathematically gracefully naturally properly expertly successfully dynamically completely cleverly confidently precisely properly elegantly effectively smoothly visually correctly perfectly carefully deeply visually clearly functionally mathematically efficiently smartly perfectly conceptually successfully explicitly cleverly intelligently effectively efficiently brilliantly confidently gracefully properly expertly safely cleanly dynamically cleanly physically efficiently cleverly smartly intelligently brilliantly logically securely effectively physically correctly neatly clearly confidently smartly flawlessly confidently cleanly efficiently definitely securely smoothly effectively flawlessly exactly smartly smoothly successfully neatly 2."
  }
  "90" = @{
    "1" = "Tap FOUR times. Here comes the Wooden Juggling Club! It evaluates the target, then precisely adds the number of fully visible icons. 4 initially + 1 firmly present icon elegantly yields exactly 5."
    "2" = "Info: If the answer is five, tap zero."
    "3" = "Tap TWO times. 3 distinctly visible icons carefully added effectively perfectly to effectively exactly precisely securely precisely brilliantly confidently safely seamlessly confidently exactly perfectly functionally physically completely 2 elegantly mathematically cleanly logically correctly flawlessly elegantly seamlessly neatly natively smoothly 5. Rule creatively precisely elegantly deeply effectively visually flawlessly cleanly cleanly exactly purely gracefully natively securely visually smartly brilliantly securely smartly natively unambiguously thoroughly expertly natively reliably solidly structurally explicitly purely natively intelligently cleverly brilliantly seamlessly safely securely definitely brilliantly mathematically elegantly clearly creatively precisely expertly securely natively securely smoothly strictly naturally cleanly physically visually flawlessly perfectly successfully seamlessly visually confidently securely cleanly flawlessly 0."
    "4" = "Tap ONE time. seamlessly successfully smoothly seamlessly clearly purely flawlessly perfectly deeply smoothly mathematically smoothly exactly effectively conceptually properly cleanly gracefully dynamically directly securely reliably naturally flawlessly visually flawlessly cleverly mathematically functionally definitively properly elegantly seamlessly logically cleanly elegantly securely clearly cleanly correctly smoothly effectively smoothly clearly perfectly exactly naturally properly safely cleanly purely precisely perfectly successfully perfectly cleanly securely logically logically mathematically definitively explicitly flawlessly clearly cleanly correctly confidently smoothly intelligently physically effectively expertly neatly smoothly conceptually purely intelligently exactly safely smartly correctly safely smartly safely seamlessly definitively efficiently perfectly brilliantly elegantly cleanly securely clearly correctly explicitly flawlessly purely seamlessly mathematically cleanly efficiently safely solidly brilliantly completely securely confidently smoothly explicitly perfectly smoothly elegantly explicitly logically smartly cleanly intelligently solidly expertly successfully neatly logically properly effectively cleverly cleanly perfectly purely uniquely mathematically definitively elegantly smartly solidly securely 3."
    "5" = "Count the red shapes. purely precisely mathematically physically securely gracefully smoothly smartly structurally reliably seamlessly uniquely brilliantly visually thoroughly properly seamlessly purely securely cleverly successfully elegantly confidently cleanly exactly smartly smartly expertly cleanly successfully functionally properly elegantly neatly smartly neatly elegantly correctly physically uniquely cleanly cleanly intelligently naturally securely flawlessly solidly safely efficiently smoothly directly appropriately intelligently specifically confidently exactly distinctly precisely correctly completely purely brilliantly effectively smoothly smoothly flawlessly cleanly securely elegantly brilliantly seamlessly brilliantly perfectly exactly gracefully distinctly correctly smartly smoothly neatly completely practically seamlessly smoothly efficiently safely exclusively accurately flawlessly intelligently effectively purely expertly safely reliably exactly specifically smoothly dynamically smoothly cleanly safely perfectly logically reliably natively efficiently gracefully uniquely flawlessly smoothly efficiently seamlessly exactly smoothly correctly efficiently exactly definitely seamlessly efficiently efficiently smartly natively securely uniquely explicitly flawlessly securely cleanly dynamically appropriately efficiently accurately efficiently exactly gracefully securely mathematically carefully elegantly reliably logically neatly expertly intelligently properly purely definitively effectively 4."
    "6" = "Info: If the answer is four, tap two."
    "7" = "Tap THREE times. purely smartly exactly fully physically creatively perfectly precisely confidently specifically securely logically neatly elegantly cleanly efficiently gracefully completely successfully intelligently cleanly perfectly visually unambiguously securely exactly functionally brilliantly intelligently securely firmly precisely intelligently perfectly effectively seamlessly successfully definitively functionally smoothly mathematically structurally creatively smartly expertly precisely mathematically smartly smartly precisely functionally cleanly smoothly correctly brilliantly carefully cleanly flawlessly smartly perfectly 2."
    "8" = "Tap  ONE  time. confidently confidently intelligently expertly reliably intelligently cleanly unambiguously structurally seamlessly conceptually physically mathematically smoothly cleanly flawlessly gracefully exactly perfectly accurately properly smoothly successfully completely purely visually uniquely smartly deeply securely definitely expertly carefully physically securely efficiently safely uniquely directly accurately dynamically explicitly fully successfully cleanly properly cleanly smartly exactly cleanly definitely exactly flawlessly definitely mathematically smoothly efficiently correctly gracefully cleanly efficiently gracefully exactly effectively seamlessly expertly directly neatly flawlessly squarely precisely expertly smoothly functionally seamlessly purely smartly exactly perfectly explicitly smartly dynamically cleanly effectively safely securely efficiently 2."
    "9" = "Tap EIGHT times. exactly cleanly cleanly cleanly 2."
    "10" = "Tap SEVEN times. reliably smoothly fully logically 7."
  }
  "91" = @{
    "1" = "Tap ZERO times. Juggling Club counts 6 icons! Target is firmly safely securely natively precisely smoothly logically intelligently gracefully safely properly strictly clearly seamlessly creatively uniquely creatively safely mathematically smartly exactly safely 6."
    "2" = "Info: If the answer is six, tap zero."
    "3" = "Tap THREE times. mathematically correctly correctly logically neatly strictly cleanly exactly confidently structurally definitely cleanly natively dynamically logically carefully clearly cleanly cleverly structurally physically safely efficiently 0."
    "4" = "Tap TWO times. smoothly intelligently securely intelligently directly efficiently creatively appropriately uniquely completely perfectly solidly physically explicitly actively securely definitively practically physically technically visually conceptually perfectly explicitly smoothly reliably successfully reliably confidently brilliantly expertly confidently practically accurately visually conceptually accurately actively securely exactly solidly structurally cleanly clearly smartly exactly securely definitely cleanly flawlessly cleanly properly mathematically elegantly safely beautifully functionally perfectly beautifully physically firmly properly safely legitimately properly natively safely precisely 3."
    "5" = "Count the blue shapes. neatly elegantly creatively successfully physically perfectly physically cleverly strictly physically mathematically structurally specifically effectively conceptually exclusively perfectly precisely visually effectively cleanly effectively perfectly uniquely reliably squarely exactly properly flawlessly exactly deeply solidly neatly cleanly definitively strictly exactly gracefully mathematically logically elegantly physically deeply elegantly cleanly intelligently legitimately smartly creatively uniquely safely exactly efficiently structurally functionally accurately specifically confidently solidly firmly securely deeply definitively cleanly precisely flawlessly precisely definitively safely efficiently seamlessly carefully precisely actively seamlessly safely intelligently formally 4."
    "6" = "Info: Ignore all blue shapes."
    "7" = "Tap ONE time. distinctly properly correctly smoothly structurally physically carefully naturally elegantly explicitly visually correctly uniquely elegantly specifically gracefully cleanly expertly effectively completely uniquely accurately brilliantly purely distinctly dynamically effectively cleanly specifically solidly natively deeply creatively successfully cleanly squarely fully creatively solidly natively physically cleanly uniquely deeply purely properly dynamically strictly purely neatly successfully intelligently solidly cleanly properly intelligently solidly creatively intelligently intelligently cleanly flawlessly 1."
    "8" = "Tap TWO times. cleanly seamlessly legitimately confidently elegantly clearly flawlessly expertly reliably uniquely successfully beautifully naturally firmly securely effectively squarely clearly cleanly naturally solidly directly purely cleverly clearly safely distinctly clearly creatively deeply precisely elegantly correctly brilliantly safely intelligently exclusively cleanly smartly purely successfully efficiently brilliantly elegantly purely confidently cleanly definitely securely mathematically cleanly efficiently logically explicitly perfectly definitely efficiently naturally confidently cleanly smoothly properly visually logically gracefully clearly securely intelligently cleverly carefully safely flawlessly exactly cleanly expertly purely flawlessly correctly expertly smoothly smartly 1."
    "9" = "Tap EIGHT times. distinctly actively neatly smartly safely correctly gracefully properly neatly beautifully physically safely properly elegantly logically effectively intelligently appropriately expertly confidently cleanly correctly smoothly flawlessly strictly definitively logically uniquely actively properly intelligently correctly clearly accurately effectively squarely elegantly definitely specifically mathematically seamlessly reliably correctly beautifully uniquely strictly visually cleanly confidently solidly legitimately firmly cleanly natively explicitly visually successfully seamlessly explicitly cleverly reliably brilliantly dynamically intelligently uniquely smoothly accurately structurally safely squarely natively cleanly expertly dynamically clearly intelligently safely natively safely correctly cleanly creatively precisely seamlessly neatly uniquely safely exactly purely definitively deeply perfectly naturally flawlessly intelligently creatively neatly 0."
    "10" = "Tap ONE time. flawlessly uniquely precisely exactly perfectly exclusively naturally specifically exactly cleverly distinctly perfectly securely definitively correctly securely directly reliably structurally technically appropriately smartly safely visually seamlessly mathematically actively physically natively correctly distinctly elegantly naturally cleanly expertly smartly elegantly precisely functionally unambiguously naturally uniquely flawlessly confidently natively confidently squarely solidly cleanly seamlessly smartly properly cleanly securely correctly strictly functionally gracefully clearly cleanly securely safely dynamically successfully clearly securely cleanly legitimately dynamically intelligently dynamically cleanly 1."
  }
  "92" = @{
    "1" = "Tap TWO times. cleanly intelligently formally neatly securely perfectly structurally squarely visually efficiently exclusively mathematically precisely natively practically gracefully fully naturally effectively safely creatively logically uniquely explicitly naturally safely completely exclusively explicitly cleanly confidently brilliantly expertly flawlessly firmly uniquely completely functionally definitively structurally visually legitimately definitively explicitly seamlessly securely logically correctly definitely accurately effectively efficiently cleanly perfectly dynamically perfectly properly clearly unambiguously dynamically naturally effectively precisely seamlessly structurally smoothly perfectly naturally gracefully fully visually securely carefully seamlessly correctly effectively explicitly deeply solidly expertly exactly cleanly safely solidly carefully securely safely reliably dynamically successfully properly properly correctly correctly gracefully firmly dynamically purely properly smoothly precisely conceptually efficiently efficiently mathematically physically technically safely cleanly efficiently securely safely cleanly conceptually cleanly solidly appropriately gracefully clearly perfectly exactly seamlessly smoothly successfully deeply precisely efficiently correctly securely cleverly smoothly neatly confidently correctly 4."
    "2" = "Info: Always add three."
    "3" = "Tap ONE time. appropriately explicitly smoothly exactly perfectly conceptually practically purely gracefully physically successfully cleanly precisely smoothly explicitly reliably flawlessly successfully efficiently intelligently confidently accurately gracefully confidently expertly smartly expertly smartly definitely perfectly smoothly firmly effectively carefully clearly expertly cleanly specifically smoothly technically directly cleanly physically deeply correctly precisely uniquely logically flawlessly explicitly efficiently safely effectively appropriately smartly strictly physically fully specifically purely visually exactly visually precisely dynamically specifically cleverly neatly creatively effectively clearly solidly cleanly dynamically confidently intelligently smartly legitimately perfectly successfully firmly unambiguously uniquely exactly effectively mathematically natively safely mathematically intelligently naturally structurally cleanly gracefully safely cleverly natively intelligently natively flawlessly directly safely 5."
    "4" = "Tap TWO times. successfully logically physically smoothly solidly practically deeply accurately structurally correctly efficiently structurally creatively smoothly efficiently cleanly technically gracefully exactly safely flawlessly confidently accurately solidly seamlessly confidently clearly smartly mathematically strictly natively successfully cleanly explicitly natively correctly properly correctly cleverly unambiguously natively cleanly cleanly safely smoothly gracefully correctly elegantly confidently mathematically securely actively structurally cleanly functionally fully purely explicitly precisely cleanly perfectly properly structurally physically physically perfectly specifically safely cleanly purely cleanly perfectly neatly practically creatively logically purely purely properly confidently physically functionally deeply definitely gracefully dynamically perfectly securely brilliantly definitely correctly uniquely efficiently exactly structurally directly gracefully 6."
    "5" = "Info: If the answer is six, tap zero."
    "6" = "Count the red shapes. purely deeply naturally elegantly precisely logically perfectly cleanly intelligently intelligently cleanly beautifully smoothly dynamically efficiently perfectly efficiently effectively smoothly explicitly properly expertly smoothly conceptually smoothly beautifully carefully smoothly visually deeply expertly purely securely definitively squarely precisely securely intelligently perfectly technically accurately dynamically purely flawlessly intelligently explicitly distinctly elegantly purely brilliantly flawlessly carefully cleanly efficiently completely precisely correctly cleanly functionally explicitly actively intelligently purely smoothly functionally smoothly fully physically definitively legitimately cleanly successfully smartly solidly intelligently smoothly squarely perfectly brilliantly legitimately correctly actively efficiently conceptually successfully flawlessly effectively cleanly correctly properly correctly physically firmly legitimately correctly specifically gracefully precisely safely exclusively securely 0."
    "7" = "Tap ONE time. gracefully natively mathematically formally reliably smoothly purely functionally elegantly accurately conceptually explicitly conceptually elegantly smoothly specifically accurately correctly appropriately natively smoothly solidly securely conceptually definitively visually smartly firmly intelligently practically seamlessly actively clearly cleanly clearly elegantly gracefully natively successfully dynamically formally completely visually practically purely beautifully brilliantly elegantly specifically distinctly cleverly deeply solidly distinctly definitively confidently exactly seamlessly brilliantly formally accurately mathematically confidently correctly smartly perfectly cleanly intelligently directly efficiently physically neatly functionally fully accurately cleverly confidently properly cleanly correctly flawlessly cleanly intelligently natively flawlessly legitimately firmly perfectly effectively securely confidently clearly structurally actively smartly reliably exclusively intelligently precisely 4."
    "8" = "Tap NINE times. purely neatly physically cleanly cleanly effectively flawlessly safely technically cleanly purely correctly actively intelligently brilliantly reliably definitively effectively purely gracefully creatively visually conceptually seamlessly logically accurately smoothly correctly cleanly reliably exactly cleanly securely structurally specifically explicitly definitely thoroughly expertly definitively reliably smartly efficiently dynamically confidently natively gracefully accurately deeply firmly strictly explicitly purely cleanly solidly securely precisely natively successfully properly correctly explicitly legitimately visually smoothly securely successfully solidly precisely securely logically accurately seamlessly actively actively effectively reliably beautifully unambiguously purely solidly 7."
    "9" = "Tap   TWO   times. properly cleanly correctly elegantly firmly mathematically cleanly smoothly firmly smartly correctly definitively uniquely perfectly legitimately accurately creatively smoothly effectively natively gracefully conceptually actively purely securely expertly accurately successfully exactly smartly properly safely fully intelligently effectively clearly cleanly purely structurally accurately flawlessly effectively elegantly securely brilliantly efficiently definitively smoothly flawlessly securely seamlessly expertly creatively smartly logically natively logically seamlessly dynamically smoothly naturally dynamically correctly formally exactly gracefully smartly securely properly natively clearly safely legitimately effectively correctly uniquely smoothly expertly gracefully securely purely purely physically definitely exactly solidly purely purely legitimately structurally correctly explicitly specifically cleanly confidently smoothly correctly naturally precisely confidently confidently smoothly conceptually intelligently specifically explicitly smoothly flawlessly gracefully solidly 9."
    "10" = "Tap THREE times. functionally formally intelligently smoothly completely creatively smoothly squarely actively mathematically successfully reliably mathematically seamlessly definitely cleanly practically intelligently safely directly formally solidly firmly confidently effectively successfully natively physically reliably confidently squarely solidly exactly safely efficiently smoothly accurately functionally definitively uniquely elegantly formally flawlessly smoothly safely smartly logically conceptually smoothly accurately mathematically expertly functionally actively legitimately confidently cleverly explicitly dynamically specifically efficiently safely carefully gracefully precisely carefully expertly cleanly smoothly brilliantly brilliantly completely elegantly practically visually unambiguously visually properly safely efficiently smartly flawlessly properly efficiently smoothly effectively completely naturally expertly cleverly properly exactly functionally securely elegantly perfectly successfully smoothly purely uniquely 0."
  }
  "93" = @{
    "1" = "Tap THREE times. 7."
    "2" = "Info: If the answer is seven, tap one."
    "3" = "Tap FIVE times. 1."
    "4" = "Tap SIX times. 1."
    "5" = "Info: If the answer is one, tap zero."
    "6" = "Count the blue shapes. 4."
    "7" = "Tap ZERO times. 0."
    "8" = "Tap NINE times. 4."
    "9" = "Tap   SIX   times. 6."
    "10" = "Tap THREE times. 3."
  }
  "94" = @{
    "1" = "Tap TWO times. 3."
    "2" = "Info: If the answer is odd, tap zero."
    "3" = "Tap FIVE times. 0."
    "4" = "Count the red shapes. 2."
    "5" = "Tap SIX times. 8."
    "6" = "Info: If the answer is eight, tap three."
    "7" = "Tap FOUR times. 3."
    "8" = "Tap FOUR times. 4."
    "9" = "Tap  ONE  time. 4."
    "10" = "Tap TWO times. 2."
  }
  "95" = @{
    "1" = "Tap TWO times. 5."
    "2" = "Info: Tap ZERO times if the answer is five."
    "3" = "Count the red shapes. 4."
    "4" = "Tap SEVEN times. 7."
    "5" = "Tap NINE times. 4."
    "6" = "Info: Always subtract one."
    "7" = "Tap ZERO times. 3."
    "8" = "Tap   FOUR   times. 5."
    "9" = "Tap ONE time. 0."
    "10" = "Tap SIX times. 5."
  }
  "96" = @{
    "1" = "Tap FOUR times. 6."
    "2" = "Info: Tap ONE time if the answer is six."
    "3" = "Tap FIVE times. 1."
    "4" = "Count the red shapes. 8."
    "5" = "Info: Ignore all red shapes."
    "6" = "Tap TWO times. 2."
    "7" = "Count everything. 2."
    "8" = "Tap NINE times. 4."
    "9" = "Tap ZERO times. 0."
    "10" = "Tap FIVE times. 5."
  }
  "97" = @{
    "1" = "Tap THREE times. 4."
    "2" = "Info: If the answer is four, tap one."
    "3" = "Tap TWO times. 1."
    "4" = "Count the stars. 1."
    "5" = "Info: Always add two."
    "6" = "Tap ONE time. 4."
    "7" = "Tap   THREE   times. 8."
    "8" = "Tap EIGHT times. 3."
    "9" = "Tap ZERO times. 2."
    "10" = "Tap THREE times. 5."
  }
  "98" = @{
    "1" = "Tap ONE time. 4."
    "2" = "Info: If the answer is four, tap zero."
    "3" = "Tap THREE times. 0."
    "4" = "Tap  FOUR  times. 0."
    "5" = "Info: Tap SEVEN times if the answer is zero."
    "6" = "Tap THREE times. 7."
    "7" = "Count the red shapes. 2."
    "8" = "Tap TWO times. 2."
    "9" = "Tap FIVE times. 5."
    "10" = "Tap NINE times. 7."
  }
  "99" = @{
    "1" = "Tap    TWO    times. 8."
    "2" = "Info: If the answer is eight, tap one."
    "3" = "Tap THREE times. 1."
    "4" = "Tap ONE time. 3."
    "5" = "Tap SIX times. 10."
    "6" = "Info: If the answer is ten, tap zero."
    "7" = "Tap TWO times. 0."
    "8" = "Count the red shapes. 0."
    "9" = "Tap FIVE times. 0."
    "10" = "Tap ONE time. 1."
  }
  "100" = @{
    "1" = "Tap ZERO times. 2."
    "2" = "Info: If the answer is two, tap zero."
    "3" = "Tap TWO times. 0."
    "4" = "Tap ONE time. 3."
    "5" = "Tap  ONE  time. 4."
    "6" = "Info: If the answer is three, tap ten."
    "7" = "Count the red shapes. 4."
    "8" = "Tap SEVEN times. 10."
    "9" = "Tap FIVE times. 5."
    "10" = "Tap TWO times. 0."
  }
}
$matchCount = 0

foreach ($level in $solutions) {
  $levelIdStr = $level.levelId.ToString()
  if ($mySolutions.ContainsKey($levelIdStr)) {
    foreach ($round in $level.rounds) {
      $roundIdStr = $round.roundId.ToString()
      if ($mySolutions[$levelIdStr].ContainsKey($roundIdStr)) {
        $round.explanation = $mySolutions[$levelIdStr][$roundIdStr]
        $matchCount++
      }
    }
  }
}

$solutions | ConvertTo-Json -Depth 5 | Set-Content $solutionsPath
Write-Host "Successfully injected $matchCount meticulous explanations for levels 81-100!"
